parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\UI\Shared\Http\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Component\MailerService\Application\Service\MailerService:
        arguments:
            $senderAddress: '%env(resolve:SENDER_ADDRESS)%'